name: 코드 품질 검사

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint-and-test:
    name: 린트 및 테스트
    runs-on: ubuntu-latest
    
    steps:
      - name: 소스 코드 체크아웃
        uses: actions/checkout@v3
      
      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: 클라이언트 종속성 설치
        run: cd client && npm ci
      
      - name: ESLint 검사
        run: cd client && npm run lint
      
      - name: 테스트 실행
        run: cd client && npm test
        env:
          CI: true 