name: Deploy Infrastructure

on:
  workflow_dispatch:
  push:
    branches: [main, master]
    paths:
      - 'terraform/**'

jobs:
  deploy:
    name: 인프라 배포 (Terraform)
    runs-on: ubuntu-latest
    
    steps:
      - name: 소스 코드 체크아웃
        uses: actions/checkout@v3
      
      - name: AWS 자격 증명 설정
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Terraform 설정
        uses: hashicorp/setup-terraform@v2
      
      - name: Terraform 초기화
        run: |
          cd terraform
          terraform init
        env:
          TF_VAR_mongodb_atlas_public_key: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
          TF_VAR_mongodb_atlas_private_key: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
          TF_VAR_mongodb_atlas_org_id: ${{ secrets.MONGODB_ATLAS_ORG_ID }}
          TF_VAR_db_password: ${{ secrets.MONGODB_PASSWORD }}
      
      - name: Terraform 계획
        run: |
          cd terraform
          terraform plan
        env:
          TF_VAR_mongodb_atlas_public_key: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
          TF_VAR_mongodb_atlas_private_key: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
          TF_VAR_mongodb_atlas_org_id: ${{ secrets.MONGODB_ATLAS_ORG_ID }}
          TF_VAR_db_password: ${{ secrets.MONGODB_PASSWORD }}
      
      - name: Terraform 적용
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          cd terraform
          terraform apply -auto-approve
        env:
          TF_VAR_mongodb_atlas_public_key: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
          TF_VAR_mongodb_atlas_private_key: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
          TF_VAR_mongodb_atlas_org_id: ${{ secrets.MONGODB_ATLAS_ORG_ID }}
          TF_VAR_db_password: ${{ secrets.MONGODB_PASSWORD }}
      
      - name: MongoDB 연결 문자열 저장
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          MONGODB_URI=$(cd terraform && terraform output -raw connection_string)
          echo "MONGODB_URI=${MONGODB_URI}" >> $GITHUB_ENV
          echo "::add-mask::${MONGODB_URI}"
      
      - name: GitHub Secrets 업데이트
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: gliech/create-github-secret-action@v1
        with:
          name: MONGODB_URI
          value: ${{ env.MONGODB_URI }}
          pa_token: ${{ secrets.GH_PA_TOKEN }} 